### ISSUE TITLE
Query settings not creating appropriate index

### ISSUE THREAD

**Issue by rj3d** [sebelga/gstore-node#88]
Hey there! I think this is a bug, as the documentation does not mention having to create indexes for queries.

I have an example model that looks like this:

```
const gstore = require('gstore-node')();
const Schema = gstore.Schema;

const itemSchema = new Schema({
    name: { type: 'string', required: true },
    arrOfObjs: {
        type: 'array',
        validate: {
            rule: validateArrOfObjs,
        }
    },
    createdOn: { type: 'string', default: gstore.defaultValues.NOW, write: false, read: false }
});

function validateArrOfObjs(obj, validator) {
    if (!Array.isArray(obj)) {
        return false;
    }

    var allObjs = obj.every((item) => {
        return item !== null && typeof item === 'object';
    });

    return allObjs;
};

const itemQuerySettings = {
    order : { property: 'createdOn', descending: true }, // descending defaults to false and is optional
    select : ['name', 'createdOn']
};

// Add settings to schema
itemSchema.queries('list', itemQuerySettings)

const Item = gstore.model('Item', itemSchema);
export default Item;
```

If I create a few items and then try to list them with the following endpoint:

```
const listItems = (req, res) => {
  Item.list()
    .then((response) => {
      res.json({
        entities: response.entities,
        nextPageCursor: response.nextPageCursor
      });
    });
};
```

I get the following error:

```
(node:14987) UnhandledPromiseRejectionWarning: Error: no matching index found. recommended index is:
- kind: Item
  properties:
  - name: createdOn
    direction: desc
  - name: name

    at ./node_modules/grpc/src/client.js:554:15
```

On node v9.3.0, Yarn package.json:
```
{
  "name": "gstore-poc",
  "version": "1.0.0",
  "description": "POC for gstore library",
  "main": "index.js",
  "scripts": {
    "api": "babel-node server.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "babel-preset-env": "^1.6.1",
    "body-parser": "^1.18.2",
    "express": "^4.16.2",
    "gstore-node": "^2.1.4",
    "mongoose": "^5.0.0-rc1",
    "morgan": "^1.9.0"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0"
  },
  "babel": {
    "presets": [
      "env"
    ]
  }
}
```
